# Generated by Django 5.2.3 on 2025-06-16 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pferd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transponder_id', models.CharField(max_length=50, unique=True)),
                ('paddock_nummer', models.CharField(max_length=10)),
                ('bild', models.ImageField(blank=True, null=True, upload_to='pferde/')),
            ],
        ),
        migrations.CreateModel(
            name='Fuetterung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_zeit', models.TimeField()),
                ('end_zeit', models.TimeField()),
                ('pferd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuetterungen', to='stall.pferd')),
            ],
        ),
        migrations.CreateModel(
            name='ZugangHistorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitpunkt', models.DateTimeField(auto_now_add=True)),
                ('pferd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stall.pferd')),
            ],
        ),
    ]
