# Generated by Django 5.2.3 on 2025-06-16 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zutritt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit', models.DateTimeField(auto_now_add=True)),
                ('pferd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zutritte', to='stall.pferd')),
            ],
        ),
    ]
